### ISSUE TITLE
Contest start time

### ISSUE THREAD

**Issue by dxtvzw** [TobxD/codeforces_live_bot#4]
There is an issue with the bot when it sends notificaitons about the time of start of a contest. The time of the notification (when the message is sent) and the time till the contest's start are correct, but the time of the contest itself is incorrect. For example, if a contest starts at 20:35 in some time zone, the bot writes 20:05 in its message and this happens for every contest it notifies about.

**Comment by TobxD** [comment]
Thank you for reporting this.
I have not encountered this problem so far in any timezone. What timezone did you set the bot to in the settings? Can you verify it is the correct one and tell me which one it is? Maybe there is a problem with this specific time zone.

**Comment by dxtvzw** [comment]
I'm sorry, it actually turned out that the set up time zone was incorrect. After fixing the time zone everything worked fine again.
